module.exports = {
  name: 'ELYRA',
  product: '2.0.0',
  platform: '1.9.1',
  codename: 'PC-NLU',
  phase: '1.9.1',
  label: 'ELYRA 1.9.1 — PC control NLU + Brain v2',
  releasedAt: '2026-08-10',
  capabilities: {
    conversation: true,
    voice: true,
    brainLocal: true,
    brainV2: true,
    pcControl: true,
    pcNlu: true,
    webSearch: true,
    localIntelligence: true,
    rag: true,
    tools: true,
    agent: true,
  },
};
