module.exports = {
  name: 'ELYRA',
  product: '2.0.0',
  platform: '1.7.1',
  codename: 'StableVoice',
  phase: '1.7.1',
  label: 'ELYRA 1.7.1 — Hybrid voice stable',
  releasedAt: '2026-08-10',
  capabilities: {
    conversation: true,
    voice: true,
    voicePro: true,
    voiceHybrid: true,
    voiceNoApiKey: true,
    pcControl: true,
    webSearch: true,
    localIntelligence: true,
    memoryBasic: true,
    memoryStructured: true,
    tools: true,
    agent: true,
    toolPermissions: true,
    llmResilience: true,
    rag: true,
    filesReliable: true,
    vision: true,
    ocr: true,
    multiAgent: true,
    formalEval: true,
    trainingPipeline: true,
    systemDatabase: true,
    securityHarden: true,
    nativePermissionDialogs: true,
    labTemplates: true,
    visionUi: true,
  },
};
