module.exports = {
  name: 'ELYRA',
  product: '2.0.0',
  platform: '1.5.0',
  codename: 'TrainReady',
  phase: '1.5',
  label: 'ELYRA 1.5 — Training Foundation',
  releasedAt: '2026-08-10',
  capabilities: {
    conversation: true,
    voice: true,
    voicePro: true,
    pcControl: true,
    webSearch: true,
    localIntelligence: true,
    memoryBasic: true,
    memoryStructured: true,
    tools: true,
    agent: true,
    toolPermissions: true,
    llmResilience: true,
    rag: true,
    filesReliable: true,
    vision: true,
    ocr: true,
    multiAgent: true,
    formalEval: true,
    trainingPipeline: true,
    systemDatabase: true,
    securityHarden: true,
    nativePermissionDialogs: true,
  },
};
